**implement logic to sort the data according to the total marks**
highest marks to lowest marks

In [3]:
students = [['ram',10,20,15],['raju',5,25,25],['lakshmi',5,10,15]]

# implement logic

#o/p [['raju',5,25,25],['ram',10,20,15],['lakshmi',5,10,15]]

**Today topic**
1. Numpy 


Numpy is the numerical python module to perform numerical operations


it can give access to manipulate multidimention array

In [5]:
import numpy as np

**creating simple array**

In [6]:
content = [1,2,4,5,6]

array = np.array(content)

In [7]:
print(array)

[1 2 4 5 6]


**numpy array very fast to manipulate data**

In [8]:
print(type(array))

<class 'numpy.ndarray'>


In [9]:
array = np.array([1.5, 2.5, 3.5])
array

array([1.5, 2.5, 3.5])

**To find type of data inside array**

In [10]:
array.dtype

dtype('float64')

In [11]:
array = np.array([1,2,3,4])
array

array([1, 2, 3, 4])

In [12]:
array.dtype

dtype('int32')

In [15]:
array.astype(float)

array([1., 2., 3., 4.])

In [16]:
array.dtype

dtype('int32')

**I want create array contains from 10 to 50**

In [17]:
array = np.arange(10,50,1)
array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [19]:
array = np.arange(50,10,-1)
array

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11])

In [20]:
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [21]:
array.shape

(5,)

In [22]:
row1 = [1,2,3]
row2 = [4,5,6]
row3 = [7,8,9]

array = np.array([row1,row2,row3])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
array.shape

(3, 3)

In [24]:
row1 = [1,2,3]
row2 = [4,5,6]


array = np.array([row1,row2])
print(array)

[[1 2 3]
 [4 5 6]]


In [25]:
array.shape

(2, 3)

In [26]:
array = np.array([1,2,3,4,5,6,7,8,9])
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
array.shape

(9,)

**Is it possible to allign 9 elements into 3 by 3 array**

In [28]:
array.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
print(array)

[1 2 3 4 5 6 7 8 9]


**dimension of the array**

In [31]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
array.ndim

1

In [32]:
array = np.array([[1,2,3],[4,5,6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
array.ndim

2

**to create array with values zero**

In [36]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
array=np.array([1,2,3,4,5,6,7,8,9])
r=array.reshape(3,3)
print(r.ndim)

2


In [38]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
identityArray = np.eye(3,3)
identityArray

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
identityArray.diagonal()

array([1., 1., 1.])

In [43]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

**Matematical Operations with arrays**

In [44]:
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

**I want to add 10 marks for each item in this array**

In [45]:
array + 10

array([11, 12, 13, 14, 15])

In [46]:
array

array([1, 2, 3, 4, 5])

In [47]:
array += 10
array

array([11, 12, 13, 14, 15])

In [48]:
array *= 5
array 

array([55, 60, 65, 70, 75])

In [49]:
array - 10

array([45, 50, 55, 60, 65])

In [50]:
array / 5

array([11., 12., 13., 14., 15.])

**Indexing or accessing required items from array**

In [51]:
array = np.arange(1,10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**How to access item/value 4**

In [52]:
array[3]

4

In [53]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**update value 4 with 10**

In [54]:
array[3] = 10
array

array([ 1,  2,  3, 10,  5,  6,  7,  8,  9])

In [56]:
array = array.reshape(3,3)

In [57]:
array

array([[ 1,  2,  3],
       [10,  5,  6],
       [ 7,  8,  9]])

**Access 2nd row that is at index 1**

In [58]:
array[1]

array([10,  5,  6])

**Access 2nd row 2nd item that value 5**

In [60]:
array[1][1]

5

syntax
```
array[rowIndex,columnIndex]
```

In [61]:
array[1,1]

5

How to get 2nd row and remaining rows

In [62]:
array

array([[ 1,  2,  3],
       [10,  5,  6],
       [ 7,  8,  9]])

In [63]:
array[1:,]

array([[10,  5,  6],
       [ 7,  8,  9]])

**How to access 2nd and 3rd column**

In [65]:
array[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [66]:
array

array([[ 1,  2,  3],
       [10,  5,  6],
       [ 7,  8,  9]])

**Boolean masking**

**mask the array which numbers are > 5**

In [67]:
array > 5

array([[False, False, False],
       [ True, False,  True],
       [ True,  True,  True]])

**I want all items has > 5**

```
array[booleanMask]
```

In [68]:
mask = array > 5
array[mask]

array([10,  6,  7,  8,  9])

In [69]:
array

array([[ 1,  2,  3],
       [10,  5,  6],
       [ 7,  8,  9]])

In [70]:
array[1:,1:]

array([[5, 6],
       [8, 9]])

In [71]:
array[1:,1:] = 20

In [72]:
array

array([[ 1,  2,  3],
       [10, 20, 20],
       [ 7, 20, 20]])

**Generating Random numbers**

**generate 1 random number given range**

In [74]:
np.random.randint(1,100)

72

In [75]:
np.random.random(10)

array([0.78479746, 0.40409473, 0.188439  , 0.72847844, 0.12554113,
       0.98583482, 0.32521425, 0.51215654, 0.65623017, 0.80246347])

In [76]:
np.random.random(2)

array([0.38665442, 0.66520649])

In [79]:
np.random.random((2,3))

array([[0.77436799, 0.60877762, 0.29895182],
       [0.43122154, 0.13420901, 0.05774643]])

In [80]:
np.nan # not a number

nan

In [81]:
array = np.arange(1,10).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Maximum value in this array**

In [82]:
array.max()

9

In [83]:
array.min()

1

**What is the index position of maximum value**

In [84]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
array.argmax()

8

In [86]:
array.argmin()

0

In [87]:
array = np.arange(1,10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
array.sum()

45

In [90]:
array.sum()/len(array)

5.0

In [89]:
array.mean()

5.0